### ISSUE TITLE
Upgrade Patient Main page and Patient Dashboard

### ISSUE THREAD

**Issue by BruceZZhao** [timfarkas/Serenify#102]
1. Re-arrange Patient Main to align with other user interfaces
2. Move all interactive buttons from patient dashboard to patient-main
3. Upgrade mood entry to avoid repeating entry on same day
4. Add chart to show user exercises record in Patient Dashboard

**Comment by timfarkas** [comment]
feel free to close when you see fit @BruceZZhao  :))
