### ISSUE TITLE
Extra feature ideas - Please add to the list inside this item!

### ISSUE THREAD

**Issue by bielasekk** [timfarkas/Serenify#3]

**Comment by FrancescaVanegas** [comment]
Emergency Contacts – Display local helplines or national crisis hotlines depending the individuals falls below a certain threshold of “bad mental health”. Or “Need Urgent Support” button if they are in a crisis

Support Group – A space where possibly individuals with the same disorder can communicate and chat to each other about what has worked for them and possibly create relationships. (An extra safe space for them)
