### ISSUE TITLE
id_disabled issue in User

### ISSUE THREAD

**Issue by bielasekk** [timfarkas/Serenify#58]
when trying to preserve information already stored in that column while editing patient information im getting error 
"Error updating information: Value False (type <class 'numpy.bool_'>) does not conform to type <class 'bool'>."

(...)
z = user.iloc[0][10] --> this is is_disabled 
newValues =(username, email, new_password if new_password else current_password, fname, lname, x,  emergency_contact_email, emergency_contact_name, y, z) **--> im trying to preserve the information already stored in this column**
user.editRow(primaryKey=self.current_user_id, newValues=list(newValues))

Updating information only works if I overwrite it like that:

newValues =(username, email, new_password if new_password else current_password, fname, lname, x,  emergency_contact_email, emergency_contact_name, y, False) **--> here I added False instead**
user.editRow(primaryKey=self.current_user_id, newValues=list(newValues))

**Comment by timfarkas** [comment]
so it looks like this happens because you're converting the RowList into a dataframe, which converts booleans into numpy.booleans
I think if you do bool(z), that should do the trick

LMK if that works!

**Comment by timfarkas** [comment]
closing for now, pls reopen if the issue persists
