### ISSUE TITLE
BUG: Appointment Booking allows to book appointments in the past

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#88]
the calendar autoselects the first of the month, so when I go back to november it will select 1st of November, and then I can select a time and request a booking for 1st of November

Should I update the database to throw an error when inserting new appointments with dates in the past? @PeaceES  
I initially stayed away from doing that because it might cause some problems with re-inserting records of past appointments..
Might be better to handle this via front-end guardrails..

**Comment by timfarkas** [comment]
Also, appointment booking allows simultaneous appointments in different rooms. Should I add a validity check in the database for that?? @PeaceES

**Comment by PeaceES** [comment]
Thanks for spotting this Tim!! I will fix the past appointment booking issue on my end : ) 

With regard to the simultaneous appointments in the same room by separate users (I think this is what you mean), if you can address it in the backend then yes please!! 
The other conflict would be the same patient booking appointments in different rooms for the same time slot. I've already made sure that this doesn't happen (see image attached)
<img width="601" alt="Screenshot 2024-12-03 at 16 11 16" src="https://github.com/user-attachments/assets/b290722a-0c1f-4811-95cd-234fd3adb419">

**Comment by timfarkas** [comment]
ah okay perfect, it might just be that the dummy data it's showing doesn't reflect that, but that is a quick fix
(showed two appointments at the same time in different rooms for me)

**Comment by timfarkas** [comment]
> With regard to the simultaneous appointments in the same room by separate users (I think this is what you mean), if you can address it in the backend then yes please!!

I will add it to my list!

**Comment by timfarkas** [comment]
with the room + time collisions being implemented, is this issued fixed?
@PeaceES  if yes pls close :))

**Comment by timfarkas** [comment]
Hey, this seems to have persisted or been reintroduced by recent PRs, could you take a look again please?
Can still book appointments on the first of any month (in the past and also in the future in months exceeding the 1-month advance booking time limit)
@PeaceES

**Comment by timfarkas** [comment]
<img width="692" alt="image" src="https://github.com/user-attachments/assets/8dbfa6e4-86ec-4256-a552-fe6438eccaa7">

**Comment by PeaceES** [comment]
aah, this is really strange because on my end the calendar autoselects the current day (today) and all past dates are greyed out so you can't even select them: 
![image](https://github.com/user-attachments/assets/63049ef0-4f67-48ae-ac8b-6a119c57d0e1)

The code for this is in line 156 of patient/booking.py 
![image](https://github.com/user-attachments/assets/fba6a371-17a8-4697-9d2b-635e1ad39b5e)

And in patient/custom_calendar.py as well 
![image](https://github.com/user-attachments/assets/c1e5c38d-b2e6-4929-8878-a7eb8cdc27fc)

I'm on the train now so will investigate properly ASAP when I get to campus : ))

**Comment by timfarkas** [comment]
#140
