### ISSUE TITLE
BUG: Appointment Booking crashes program when upon pressing back button

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#89]
/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/User/CODING/Uni/UCL/Serenify/patientMain.py': [Errno 2] No such file or directory
(.venv) User@eduroam-int-dhcp-97-1-72 Serenify %

**Comment by bielasekk** [comment]
still an issue, it works but takes absolute ages to load the main page again

**Comment by timfarkas** [comment]
seems to be fixed on my end, awesome!
