### ISSUE TITLE
BUG: Patient Allocations - Updating MHWP doesn't seem to work

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#92]
When I allocate John Doe to DrMartin Smith and then press back, he will still be shown with Dr Brown @j-simpson1

**Comment by j-simpson1** [comment]
Tim!! Sorry you'll have to go to the admin main page and then back into the allocation section for it to update. Unfortunately I did try to implement it by destroying the selection window but it was causing me a few issues. The update does go through to the database instantly though.

**Comment by j-simpson1** [comment]
All fixed in the latest PR which is on the BugFixes branch.
