### ISSUE TITLE
BUG: Edit Patient Information & Edit MHWP Info not supporting repeated edits

### ISSUE THREAD

**Issue by timfarkas** [timfarkas/Serenify#94]
If I edit something, then save, and then try and edit something again it doesnt do anything

  File "/Users/User/CODING/Uni/UCL/Serenify/database/database.py", line 115, in wrapper
    raise RuntimeError("You are performing an action on an instance of database that has already been closed. Try opening a new Database instance or removing the close statement.")
RuntimeError: You are performing an action on an instance of database that has already been closed. Try opening a new Database instance or removing the close statement.

should be fixable by opening and closing the database locally @j-simpson1

**Comment by timfarkas** [comment]
same for mhwp

**Comment by j-simpson1** [comment]
No worries I should be able to fix that :)

**Comment by j-simpson1** [comment]
Sorry Tim, trying to replicate the bug and struggling a tad. Seems to be working this end. Can we chat through in the algorithms lecture?

**Comment by j-simpson1** [comment]
Tested it again and I don't seem to be getting any issues. I think it was probably fixed when I moved around the db.close() statements for the other issues I was working on.
